# Generated by Django 2.1.7 on 2019-02-24 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movmensalista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movmensalista',
            old_name='dt_pago',
            new_name='dt_pgto',
        ),
    ]
