# Generated by Django 2.1.7 on 2019-02-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190224_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='prorpietario',
            new_name='proprietario',
        ),
    ]
