from django.urls import path
from .views import (
	home, 
	lista_pessoas, 
	lista_veiculos, 
	lista_mov_rotativos,
	lista_mensalistas,
	lista_mov_mensalistas,
	cadastra_pessoas,
	cadastra_veiculos,
	cadastra_mov_rotativos,
	cadastra_mensalistas,
	cadastra_mov_mensalistas,
	update_pessoas,
	update_veiculos,
	update_rotativos,
	update_mensalistas,
	update_mov_mensalistas,
	delete_pessoas,
	delete_veiculos,
	delete_rotativos,
	delete_mensalistas,
	delete_mov_mensalistas, 
	)

urlpatterns = [
    path('', home, name="core_home"),
    
    path('pessoas/', lista_pessoas, name='core_lista_pessoas'),
    path('cadastra_pessoas/', cadastra_pessoas, 
    	name='core_cadastra_pessoas'),
    path('update_pessoas/<int:id>/', update_pessoas, 
    	name='core_update_pessoas'),
    path('delete_pessoas/<int:id>/', delete_pessoas, 
    	name='core_delete_pessoas'),

    path('veiculos/', lista_veiculos, name='core_lista_veiculos'),
    path('cadastra_veiculos/', cadastra_veiculos, 
    	name='core_cadastra_veiculos'),
    path('update_veiculos/<int:id>/', update_veiculos, 
    	name='core_update_veiculos'),
    path('delete_veiculos/<int:id>/', delete_veiculos, 
    	name='core_delete_veiculos'),

    path('rotativos/', lista_mov_rotativos, name='core_lista_mov_rotativos'),
    path('cadastra_rotativos/', cadastra_mov_rotativos, 
    	name='core_cadastra_mov_rotativos'),
    path('update_rotativos/<int:id>/', update_rotativos, 
    	name='core_update_rotativos'),
    path('delete_rotativos/<int:id>/', delete_rotativos, 
    	name='core_delete_rotativos'),

    path('mensalistas/', lista_mensalistas, name='core_lista_mensalistas'),
    path('cadastra_mensalistas/', cadastra_mensalistas, 
    	name='core_cadastra_mensalistas'),
    path('update_mensalistas/<int:id>/', update_mensalistas, 
    	name='core_update_mensalistas'),
    path('delete_mensalistas/<int:id>/', delete_mensalistas, 
    	name='core_delete_mensalistas'),

    path('mensal/', lista_mov_mensalistas, name='core_lista_mov_mensalistas'),
    path('cadastra_mensal/', cadastra_mov_mensalistas, 
    	name='core_cadastra_mov_mensalistas'),
    path('update_mensal/<int:id>/', update_mov_mensalistas, 
    	name='core_update_mov_mensalistas'),
    path('delete_mensal/<int:id>/', delete_mov_mensalistas, 
    	name='core_delete_mov_mensalistas'),
    ]